from __future__ import annotations

from http import HTTPStatus
from typing import Any, List, Optional

from pydantic import BaseModel, Field

PROBLEM_BASE = "https://boardgames.app/problems"
VALIDATION_PROBLEM = f"{PROBLEM_BASE}/validation-error"
UNAUTHORIZED_PROBLEM = f"{PROBLEM_BASE}/unauthorized"
NOT_FOUND_PROBLEM = f"{PROBLEM_BASE}/not-found"
SERVICE_UNAVAILABLE_PROBLEM = f"{PROBLEM_BASE}/service-unavailable"


class ProblemDetailsResponse(BaseModel):
    """
    Error payload following RFC 9457. Provides structured diagnostic information
    for validation failures, domain errors, and authentication issues.
    """

    type: Optional[str] = Field(
        None, description="A URI reference that identifies the problem type."
    )
    title: str = Field(
        ..., description="A short, human-readable summary of the problem."
    )
    status: int = Field(
        ...,
        ge=100,
        le=599,
        description="HTTP status code generated by the origin server.",
    )
    detail: Optional[str] = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem.",
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
    )
    code: Optional[str] = Field(None, description="A machine-readable error code.")
    invalid_params: Optional[List[dict[str, str]]] = Field(
        None,
        description="A list of invalid parameters with details about the validation failure.",
    )

    def __init__(
        self,
        title: str,
        /,
        *,
        status: int,
        type: str | None = "about:blank",
        **data: Any,
    ) -> None:
        if "type" in data:
            type = data.pop("type")
        super().__init__(title=title, status=status, type=type, **data)


class UnauthorizedResponse(ProblemDetailsResponse):
    """
    RFC 9457 payload for unauthorized access attempts.
    """

    def __init__(self, detail: Optional[str] = None, **data: Any) -> None:
        type_override = data.pop("type", UNAUTHORIZED_PROBLEM)
        super().__init__(
            HTTPStatus.UNAUTHORIZED.phrase,
            status=401,
            type=type_override,
            detail=detail,
            **data,
        )


class NotFoundResponse(ProblemDetailsResponse):
    """
    RFC 9457 payload for missing resources.
    """

    def __init__(
        self, title: str = HTTPStatus.NOT_FOUND.phrase, detail: Optional[str] = None, **data: Any
    ) -> None:
        type_override = data.pop("type", NOT_FOUND_PROBLEM)
        super().__init__(
            title,
            status=404,
            type=type_override,
            detail=detail,
            **data,
        )


class BadRequestResponse(ProblemDetailsResponse):
    """
    RFC 9457 payload for invalid client requests.
    """

    def __init__(
        self, title: str = HTTPStatus.BAD_REQUEST.phrase, detail: Optional[str] = None, **data: Any
    ) -> None:
        type_override = data.pop("type", VALIDATION_PROBLEM)
        super().__init__(
            title,
            status=400,
            type=type_override,
            detail=detail,
            **data,
        )
