MECHANICS_LIST = [
    "acting",
    "action event",
    "action drafting",
    "action points",
    "action queue",
    "action retrieval",
    "action timer",
    "advantage token",
    "alliances",
    "area majority influence",
    "area movement",
    "area impulse",
    "auction bidding",
    "auction compensation",
    "auction: dexterity",
    "auction: dutch",
    "auction: dutch priority",
    "auction: english",
    "auction: fixed placement",
    "auction: multiple lot",
    "auction: once around",
    "auction: sealed bid",
    "auction: turn order until pass",
    "automatic resource growth",
    "betting and bluffing",
    "bias",
    "bids as wagers",
    "bingo",
    "bribery",
    "campaign battle card driven",
    "card play conflict resolution",
    "catch the leader",
    "chaining",
    "chit pull system",
    "choreographed movement",
    "closed drafting",
    "cooperative game",
    "critical hits and failures",
    "cube tower",
    "deck construction",
    "deck bag and pool building",
    "deduction",
    "delayed purchase",
    "demand track",
    "dice rolling",
    "different dice movement types",
    "digital media",
    "enclosure",
    "end game bonuses",
    "event deck",
    "flicking",
    "final turn bonus",
    "follow",
    "force commitment",
    "grid movement",
    "hand management",
    "hidden roles",
    "hidden victory points",
    "hexagon grid",
    "hidden information",
    "hidden movement",
    "hot potato",
    "impulse movement",
    "increase value of unchosen resources",
    "increase your value when others choose",
    "indented by phase sequential turns",
    "interrupts",
    "layering",
    "legacy game",
    "line of sight",
    "load balacing",
    "loans",
    "losing actions",
    "macro actions",
    "market",
    "matching",
    "measurement movement",
    "memory",
    "modular board",
    "multi use cards",
    "multiple maps",
    "movement points",
    "multiple lots",
    "narrative choice paragraph",
    "network and route building",
    "open drafting",
    "paper and pencil",
    "pattern building",
    "pattern movement",
    "pen and paper and dice",
    "physical removal",
    "pickup and deliver",
    "player elimination",
    "point to point movement",
    "ponzi scheme",
    "prediction",
    "programmable action",
    "push your luck",
    "race",
    "random production",
    "random turn order",
    "ratio fluid turn order",
    "real time",
    "reconstruction",
    "resource to move",
    "role playing",
    "roll spin and move",
    "scenario mission campaign game",
    "score and reset game",
    "secret unit deployment",
    "semi cooperative game",
    "set collection",
    "simulation",
    "simultaneous action selection",
    "sizing up",
    "solo solitaire game",
    "stock holding",
    "storytelling",
    "take that",
    "team based game",
    "tech trees tech tracks",
    "tile placement",
    "time track",
    "track movement",
    "trading",
    "trick taking",
    "turn order: claimant",
    "turn order: role order",
    "turn order: pass order",
    "turn order: progressive",
    "turn order: random",
    "variable phase order",
    "variable player powers",
    "voting",
    "worker placement",
    "worker placement, different worker types",
    "worker placement with dice workers",
    "worker placement with restrictions",
    "written communication",
]

THEME_LIST = [
    "abstract strategy",
    "action adventure",
    "agriculture",
    "american west",
    "animals",
    "arabian",
    "aviation flight",
    "bluffing",
    "book card game",
    "camping",
    "cars racing",
    "children's game",
    "city building",
    "civil war",
    "civilization",
    "collectible components",
    "comic book strip",
    "deduction",
    "dice",
    "economic",
    "educational",
    "electronic",
    "environmental",
    "expansion for base game",
    "exploration",
    "fan expansion",
    "fantasy",
    "farming",
    "fighting",
    "game system",
    "horror",
    "humor",
    "industry manufacturing",
    "korean war",
    "mafia",
    "math",
    "mature adult",
    "maze",
    "medical",
    "medieval",
    "memory",
    "miniatures",
    "modern warfare",
    "movies tv radio theme",
    "murder mystery",
    "music",
    "mythology",
    "napoleonic",
    "nautical",
    "negotiation",
    "novel based",
    "number",
    "party game",
    "pike and shot",
    "pirates",
    "political",
    "post napoleonic",
    "prehistoric",
    "print & play",
    "puzzle",
    "racing",
    "real time",
    "religious",
    "renaissance",
    "science fiction",
    "space exploration",
    "spies secret agents",
    "sports",
    "territory building",
    "third party expansion",
    "trains",
    "transportation",
    "travel",
    "trivia",
    "video game theme",
    "vietnam war",
    "wargame",
    "word game",
    "world war i",
    "world war ii",
    "zombies",
]

GENRE_LIST = [
    "abstract",
    "card",
    "childrens",
    "customizable",
    "family",
    "party",
    "strategy",
    "thematic",
    "war",
]
